### ISSUE TITLE
Alerting en échec

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/cdtn-admin#1421]
Erreur sur le processus : 

```
yarn run v1.22.19
2024-06-05T01:30:04.075376312Z $ node --enable-source-maps --unhandled-rejections=strict ./dist/index.js
2024-06-05T01:30:05.258710671Z Error: No xlsx file found
2024-06-05T01:30:05.258756322Z     at /app/webpack:/alert-cli/src/dares/scrapping.ts:18:1
2024-06-05T01:30:05.258765909Z     at Generator.next (<anonymous>)
2024-06-05T01:30:05.258774384Z     at fulfilled (/app/webpack:/alert-cli/src/dares/scrapping.ts:4:1)
2024-06-05T01:30:05.258781582Z     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-06-05T01:30:05.299425421Z info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2024-06-05T01:30:05.299521821Z error Command failed with exit code 1.
```

**Comment by maxgfr** [comment]
Suite à un envoi d'email aux gestionnaires, le problème est réglé.

**Comment by maxgfr** [comment]
Le soucis était lié au token périmé
