### ISSUE TITLE
Ingester ne fonctionne plus

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/cdtn-admin#434]
L'ingester est en échec sur dev et prod.

Voici l'erreur remontée:

```
Error: [FICHE-SP] The F2405 from service-public is embeded in a contribution and was not found

    at /app/webpack:/ingester/src/transform/fichesServicePublic/index.js:113:1

    at Array.forEach (<anonymous>)

    at getFichesServicePublic (/app/webpack:/ingester/src/transform/fichesServicePublic/index.js:111:1)

    at main (/app/webpack:/ingester/src/cli.js:256:1)
```

Il y a eu une action sur la fiche car elle était en doublon. Elle a été déthémée.

**Comment by m-maillot** [comment]
Le problème vient d'une erreur de manipulation das l'outil d'administration. La fiche SP a été supprimé de la liste des fiches SP et cela a entrainé une erreur car elle était nécessaire pour une contrib.

Il n'y a pas d'action à réaliser, @jrduscher nous a indiqué que les contribs vont à terme ne plus utiliser les fiches SP et le problème ne pourra plus se produire.

cc @virginielastisneres @lionelB
